### PR TITLE
Add gradle wrapper validation GitHub Action

### PR DESCRIPTION
**Pull request by utzcoz**
It will be helpful to validate gradle-wrapper.jar integrity.

### CODE REVIEW

**Comment by utzcoz** [comment]
From action page, we can see following log:

```
✓ Found known Gradle Wrapper JAR files:
  70239e6ca1f0d5e3b2808ef6d82390cf9ad58d3a3a0d271677a51d1b89475857 src/conformance/gradle/wrapper/gradle-wrapper.jar
  70239e6ca1f0d5e3b2808ef6d82390cf9ad58d3a3a0d271677a51d1b89475857 src/loader/gradle/wrapper/gradle-wrapper.jar
```

All `gradle-wrapper.jar` in this repository are validated by official GitHub Action. If other contributors update `gradle-wrapper.jar` at future commits, and this Action passed, it's safe to merge commits to update `gradle-wrapper.jar`.

**Comment by utzcoz** [comment]
cc /@rpavlik . FYI, Looks like GitHub Action to build conformance Android apk works fine.

**Comment by rpavlik** [comment]
Fancy, is this often needed? Guess it helps when updating the wrapper.

**Review by rpavlik — APPROVED** [review]

**Review by rpavlik — CHANGES_REQUESTED** [review]
The file needs copyright and license headers. Apparently I didn't set up the reuse check here yet

**Comment by utzcoz** [comment]
> The file needs copyright and license headers. Apparently I didn't set up the reuse check here yet

Done.

**Comment by utzcoz** [comment]
> The file needs copyright and license headers. Apparently I didn't set up the reuse check here yet

It's one of best practice for Android project on GitHub. It will help `gradle-wrapper.jar`'s integrity if contribution is made by outer contributor, for example like me to avoid file injection dangers.

**Comment by utzcoz** [comment]
It's official page for this action: https://github.com/marketplace/actions/gradle-wrapper-validation.

**Comment by rpavlik** [comment]
Oh very good idea, I'll have to do this elsewhere too.

**Comment by utzcoz** [comment]
> Oh very good idea, I'll have to do this elsewhere too.

@rpavlik could we merge it firstly? Thanks.

**Review by rpavlik — APPROVED** [review]

**Comment by rpavlik** [comment]
Oops, sorry, didn't realize I missed it.

**Comment by utzcoz** [comment]
> Oops, sorry, didn't realize I missed it.

Thanks.

**Pull request merged**
