### PR TITLE
Added GL_SRGB8 texture format

### PR DESCRIPTION
**Pull request by JoeLudwig**

### CODE REVIEW

**Review by Wallbraker — APPROVED** [review]

**Comment by rpavlik** [comment]
This doesn't require that a runtime implement that, though, right? it just handles it in case they do?

**Comment by JoeLudwig** [comment]
> This doesn't require that a runtime implement that, though, right? it just handles it in case they do?

Yes, exactly.

**Comment by rpavlik** [comment]
I'll merge as soon as I hear from @Wallbraker that the macro usage is right.

**Review by pauloAndroid — APPROVED** [review]

**Comment by Wallbraker** [comment]
> I'll merge as soon as I hear from @Wallbraker that the macro usage is right.

@rpavlik I didn't write that code, or completely swapped that out of my head. But it sounded like it was right from Ed.

**Review by rpavlik — APPROVED** [review]
Approved on call

**Pull request merged**
